### ISSUE TITLE
Add prometheus metrics exporter endpoint

### ISSUE THREAD

**Issue by tumido** [operate-first/peribolos-as-a-service#58]

**Comment by harshad16** [comment]
The pr linked in the issue contains the service monitor which on deployment 
exposes the metrics of the application to be scraped by prothemeus of the cluster.
- Servicemonitor: https://github.com/operate-first/peribolos-as-a-service/blob/main/manifests/base/controller/servicemonitor.yaml
- Service: https://github.com/operate-first/peribolos-as-a-service/blob/main/manifests/base/controller/service.yaml

closing this issue
as the metrics exporter of the application was fullfiled.
thanks.
