### ISSUE TITLE
Create SRE dashboard for controller and pipelines

### ISSUE THREAD

**Issue by tumido** [operate-first/peribolos-as-a-service#60]
A dashboard covering the controller metrics and liveliness/readiness/scaling. And pipeline execution status success/failures etc.

Should also surface (un)installation counts, event metrics, response time, event "resolve" time (delta between event received -> pipeline complete)

**Comment by tumido** [comment]
Blocked by: #59

**Comment by tumido** [comment]
Blocked by unstable grafana https://github.com/operate-first/support/issues/604

**Comment by schwesig** [comment]
/close
cleanup after change of organisation
